version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: gazette_mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=gazette_polletin
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    container_name: gazette_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
